---
- hosts : all
  gather_facts: false
  tasks :
    - name: docker build.
      command: docker build -t rakeshirukula/loginstudent2021 .
      args:
        chdir: //home//ansadmin
    - name : docker push
      command : docker push rakeshirukula/loginstudent2021
      args:
        chdir: //home//ansadmin
    - name : docker remove image
      command : docker rmi rakeshirukula/loginstudent2021
      args:
        chdir: //home//ansadmin

