--- 
- 
  gather_facts: false
  hosts: all
  tasks: 
    - 
      args: 
        chdir: //home//ansadmin
      command: "docker container stop $(docker container ls -aq)"
      ignore_errors: true
      name: "docker stop"
    - 
      args: 
        chdir: //home//ansadmin
      command: "docker container rm $(docker container ls -aq)"
      ignore_errors: true
      name: "docker remove containers"
    - 
      args: 
        chdir: //home//ansadmin
      command: "docker rmi $(docker image ls -aq)"
      ignore_errors: true
      name: "docker remove image"
    - 
      args: 
        chdir: //home//ansadmin
      command: "docker pull rakeshirukula/loginstudent2021"
      ignore_errors: true
      name: "docker pull"
    - 
      args: 
        chdir: //home//ansadmin
      command: "docker run -d --name loginstudent -p 8080:8080 rakeshirukula/loginstudent2021:latest"
      ignore_errors: true
      name: "docker run"

