name: GitHub Actions Demo Rakesh

on:
  #push:
   # branches:
   #   - main
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Ubuntu
        - macOS

jobs:
  checkoutcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "install java"
        run: "sudo apt-get install openjdk-11-jdk -y"

      - name: "install java"
        run: "sudo apt-get install maven -y"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: "pwd"
        run: "echo $PWD"

     # - name: "build"
    #    run: "cd ThreeTier/"
        
      #- name: "build"
     #   run: "mvn clean package"


        
