name: GitHub Actions Demo Rakesh

on:
  push:
    branches:
    - dev
    
  #workflow_dispatch:
    #inputs:
      #chosen-os:
        #required: true
        #type: choice
        #options:
        #- Ubuntu
        #- macOS

jobs:
  checkoutcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "install java"
        run: "sudo apt-get install openjdk-11-jdk -y"

      - name: "install java"
        run: "sudo apt-get install maven -y"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: "pwd"
        run: |
          echo "Current Directory: $(pwd)"
          echo "Files in Current Directory:"
          ls -l
        
      - name: "build"
        run: "mvn clean package"

      - name: "build image and tags"
        run: |
          docker build -t decadetomcat .
          docker tag decadetomcat rakeshirukula/decadetomcat

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "pish"
        run: |
          docker push rakeshirukula/decadetomcat

      - name: Output Run ID
        run: echo ${{ github.run_id }}
        
      - name: Output Run Number
        run: echo ${{ github.run_number }}
        
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}

        
